### PR TITLE
Update watir-screenshot-stitch.rb

### PR DESCRIPTION
**Pull request by sandeepnagra**
onrendered option is deprecated, so replaced it with .then and it started working. I can see the output has image data now.

### CODE REVIEW

**Comment by sandeepnagra** [comment]
@samnissen - this has fixed the bug with `base64_canvas` and it returns a valid output with image data. I added a breakpoint and evaluated output value to validate it.

**Comment by samnissen** [comment]
@sandeepnagra This is really great -- I did not know the method was deprecated. I appreciate the contribution!!

So that I can test and/or validate, can you please add a test that validates the condition you're experiencing is not present? 

Also, you mentioned in #26 that you replaced the html2canvas version. Can you verify that the PR you've submitted works with the html2canvas version included in the gem (version 0.4.1)? (I was never able to get html2canvas versions 0.5.x or 1.x to work, with Firefox at least.)

**Comment by sandeepnagra** [comment]
@samnissen - I never replaced the html2canvas version in the gem. I was facing the error reported under - https://github.com/samnissen/watir-screenshot-stitch/issues/14 which is now closed.

So, I created a vendor directory in project root, downloaded latest html2canvas.js file and placed it under that folder. Once I did that the directory error was gone and gem was able to locate the js file.

Also, as mentioned in #26 , I ran the following script but the rendering it not that great especially the images on the webpage:

```
require 'watir-screenshot-stitch'

b = Watir::Browser.new :chrome
b.goto "https://advisors.massmutual.com/"

img = b.screenshot.base64_canvas(b)
png = Base64.decode64(img)
File.open('test.png', 'wb') { |f| f.write(png) }
```

Let me know if this does not address your concerns.

**Comment by samnissen** [comment]
As for this issue, thank you for the code. What I'd like to see in the PR is any kind of test in RSpec test to match this. It should fail when run before your change and succeed after. I don't know exactly how this could be formulated, but you might be able to detect the deprecation warning somehow.

As for #14: Based on what you have said, I should reopen the issue as you were unable to utilize the gem before downloading html2canvas beforehand. Is that correct?

**Comment by sandeepnagra** [comment]
@samnissen - sure, I will add some test over the weekend and update the PR.

As for #14 , it doesn't need to be reopened. I realized that I had an old version of the gem. I will test with latest version of the gem and let you know if it doesn't work.

**Comment by sandeepnagra** [comment]
I confirmed, no need to reopen #14 as with latest version of the gem I don't need a separate folder with html2canvas.js file. The result output is same though, it doesn't render any images in the screenshot. Maybe, you should add that as a note in the README file for base64_canvas method usage.

**Comment by sandeepnagra** [comment]
Ok, couple of things. In the latest version of the gem 0.6.5 I see that the onrendered option is still working and no deprecated warning is thrown. So, I am closing this pull request.

Regarding the cross domain images that don't show up in the screenshot, I found the bug here - https://github.com/niklasvh/html2canvas/issues/722

I tried the allowTaint option but it didn't work. I will keep exploring a way to make the allowTaint work.

**Pull request closed without merging**
